org: skillsunionsaravanan
app: sls-sara-2
service: sls-2

provider:
  name: aws
  region: ap-southeast-1
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
      - sqs:
          arn:
            Fn::GetAtt:
              - SaraSQSQueue
              - Arn
          batchSize: 10
          maximumBatchingWindow: 60
          functionResponseType: ReportBatchItemFailures

  users:
    handler: users.handler
    events:
      - s3:
          bucket: saraphotos-unique-12345
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpg
  dispatcher:
    handler: dispatcher.dispatch
    events:
      - sns:
          arn: !Ref SuperTopic
          topicName: sara

resources:
  Resources:
    SaraSQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: sara-sqs-queue
  
    SuperTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: sara      

plugins: 
  - serverless-offline
